set-option -g default-shell /bin/zsh
set-option -sg escape-time 10

# set active-inactive window styles
set -g window-style 'fg=colour247,bg=colour234'
set -g window-active-style 'fg=default,bg=colour233'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-online-status'
set -g @plugin 'tmux-plugins/tmux-battery'

set -g @plugin 'tmux-plugins/tmux-cpu'
set -g status-right '#{cpu_bg_color} CPU: #{cpu_icon} #{cpu_percentage} | Online: #{online_status} | #{battery_status_bg} Batt: #{battery_icon} #{battery_percentage} #{battery_remain} | %a %h-%d %H:%M '

set -g @plugin 'tmux-plugins/tmux-logging'

set -g status-right-length 150

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %
set -g mouse on
set-option -g allow-rename off
set -g history-limit 10000
set-window-option -g mode-keys vi
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
set -g monitor-activity off
set -g bell-action none

bind-key s command-prompt -p "send pane to: "   "join-pane -t '%%'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
set -g default-command "/bin/zsh"
